apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-rxqs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-rxqs
    app.kubernetes.io/part-of: tkrw-pr714-0075-0029-app
  name: devfile-sample-rxqs
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-rxqs
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-rxqs
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr714-0075-0029-tenant/tkrw-pr714-0075-0029-app/devfile-sample-rxqs@sha256:15c184e2f706d5e414da18ceb74e29a0f2ac99e073cfbfffeac419d1c1a79fad
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
